### PR TITLE
Use https to load scripts

### PR DESCRIPTION
**Pull request by benmccann**
When you try to load via http it redirects to https. This removes an unnecessary redirect improving latency and security.

### CODE REVIEW

**Comment by benmccann** [comment]
@rrag do you think this PR can be merged?

**Comment by benmccann** [comment]
@rrag would you be able to merge this one too? Thanks!

**Comment by rrag** [comment]
Hello, this code is not MIT licensed and is closed source. I do not want to accept PRs on this repo

**Comment by benmccann** [comment]
Understood. I'm happy to assign all rights from this change to you if you'd like to merge it

**Pull request closed without merging**
